{% set name = "types-Flask" %}
{% set version = "1.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-Flask-{{ version }}.tar.gz
  sha256: 1294df1615e01135c5dbba530e3f8d58918afa6796f1dee8b2143c7dd47b7970

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - types-click
    - types-jinja2
    - types-werkzeug

test:
  commands:
    - test -f $SP_DIR/flask-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for Flask
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
